// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0KpW1wCemlV2V6TVgyrF4sNfz5Vi68vY',
    appId: '1:1078049742963:web:382488efe2fa4e36fa4a06',
    messagingSenderId: '1078049742963',
    projectId: 'ridersharefirebase',
    authDomain: 'ridersharefirebase.firebaseapp.com',
    storageBucket: 'ridersharefirebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbY6T3r3O51ovQVTjRX8luVyD_HFPK3r8',
    appId: '1:1078049742963:android:a1105edc279d91b1fa4a06',
    messagingSenderId: '1078049742963',
    projectId: 'ridersharefirebase',
    storageBucket: 'ridersharefirebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkzeOIqLp8uOXvCT3O7lqqdG97riZnacg',
    appId: '1:1078049742963:ios:a64969e8341e2f45fa4a06',
    messagingSenderId: '1078049742963',
    projectId: 'ridersharefirebase',
    storageBucket: 'ridersharefirebase.appspot.com',
    iosBundleId: 'com.example.rideshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkzeOIqLp8uOXvCT3O7lqqdG97riZnacg',
    appId: '1:1078049742963:ios:b31e8531f6ca3ff4fa4a06',
    messagingSenderId: '1078049742963',
    projectId: 'ridersharefirebase',
    storageBucket: 'ridersharefirebase.appspot.com',
    iosBundleId: 'com.example.rideshare.RunnerTests',
  );
}
